/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface View {
  /**
   * View name.
   */
  name: string;
  /**
   * View schema version.
   */
  version: number;
  manifest: Manifest;
  stats?: Stats;
  georeference?: Georeference;
  fragmentTransformsOffset?: {
    x: number;
    y: number;
    z: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Manifest {
  assets: PrivateAssets;
  shared_assets: SharedAssets;
  [k: string]: unknown;
}
export interface PrivateAssets {
  pdb: PrivatePDB;
  fragments: string;
  fragments_extra: string;
  materials_ptrs?: string;
  geometry_ptrs?: string;
  texture_manifest?: string;
  [k: string]: unknown;
}
export interface PrivatePDB {
  avs?: string;
  offsets?: string;
  dbid?: string;
  [k: string]: unknown;
}
export interface SharedAssets {
  pdb: SharedPDB;
  geometry: string;
  materials: string;
  textures: string;
  global_sharding: number;
  [k: string]: unknown;
}
export interface SharedPDB {
  attrs?: string;
  values?: string;
  ids?: string;
  [k: string]: unknown;
}
export interface Stats {
  num_fragments?: number;
  num_polys?: number;
  num_materials?: number;
  num_geoms?: number;
  num_textures?: number;
  [k: string]: unknown;
}
export interface Georeference {
  positionLL84?: number[];
  refPointLMV?: number[];
  [k: string]: unknown;
}
